name: Build mkp224o-cuda

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get install -y libsodium-dev autoconf

      - uses: Jimver/cuda-toolkit@v0.2

      - name: Build
        run: |
          ./autogen.sh
          ./configure --enable-amd64-51-30k --enable-cuda
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkp224o-cuda-linux
          path: mkp224o

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libsodium
            mingw-w64-x86_64-make
            autoconf
            git

      - uses: Jimver/cuda-toolkit@v0.2

      - name: Build
        run: |
          ./autogen.sh
          ./configure NVCC='nvcc -ccbin /mingw64/bin/gcc' --enable-amd64-51-30k --enable-cuda
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkp224o-cuda-windows
          path: mkp224o.exe
